build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    # DOCKER_IMAGE: $DOCKER_IMAGE
  script:
    - echo "Building Docker image - $DOCKER_IMAGE"
    - docker build -t $DOCKER_IMAGE .
    - docker save $DOCKER_IMAGE > $CI_PROJECT_DIR/amit-angular-gitlab-app.tar
  artifacts:
    paths:
      - amit-angular-gitlab-app.tar