build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_IMAGE: amit-angular-gitlab-app:latest
  script:
    - docker build -t $DOCKER_IMAGE .